[package]
name = "What-rs"
version = "0.1.0"
edition = "2021"

# Make tests work with the name used in the tutorial
[[bin]]
name = "What-rs"
path = "src/main.rs"


[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
anyhow = "1.0.91"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.2"
assert_fs = "1.1.1"