name: build and release

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  test:
    name: Test current state
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
